(ns time-management
  (:require [clojure.test :refer :all]
            [clj-time.core :as dt]
            [machine.time-management.core :refer :all]
            [machine.time-management.market-hours :refer :all]))


(deftest test-all
  (is (= true (greater-period? :h1 :m5)))
  (is (= false (greater-period? :m5 :h1)))
  (is (= true (smaler-period? :m5 :h1)))
  (is (= false (smaler-period? :h1 :m5)))
  (is (= 60 (period->seconds :m1)))
  (is (= :m5 (seconds->period (* 5 60))))
  (is (= (dt/date-time 2015 1 1 20) (floor-time (dt/date-time 2015 1 1 20) :h1)))
  (is (= (dt/date-time 2015 1 1 20) (floor-time (dt/date-time 2015 1 1 20) 360)))
  (is (= :m15 (shift-period :m10 1)))
  (is (= :m30 (shift-period :m10 2)))
  (is (= :m5 (shift-period :m10 -1)))
  (is (= :m4 (shift-period :m10 -2)))
  (is (= :m15 (upper-period :m10)))
  (is (= :m5 (lower-period :m10)))
  (is (= (dt/date-time 2015 1 1 20) (candle-time :h1 (dt/date-time 2015 1 1 20 15))))
  (is (= (dt/date-time 2015 1 1 20) (previous-candle-time :h1 (dt/date-time 2015 1 1 21 15))))
  (is (= (dt/date-time 2015 1 1 20) (next-candle-time :h1 (dt/date-time 2015 1 1 19 15))))
  (is (true? (london-market? (dt/date-time 2015 1 1 (:open london-hours)))))
  (is (true? (london-market? (dt/date-time 2015 1 1 (dec (:close london-hours))))))
  (is (false? (london-market? (dt/date-time 2015 1 1 (:close london-hours)))))
  (is (true? (frankfurt-market? (dt/date-time 2015 1 1 (:open frankfurt-hours)))))
  (is (true? (frankfurt-market? (dt/date-time 2015 1 1 (dec (:close frankfurt-hours))))))
  (is (false? (frankfurt-market? (dt/date-time 2015 1 1 (:close frankfurt-hours)))))
  (is (true? (new-york-market? (dt/date-time 2015 1 1 (:open new-york-hours)))))
  (is (true? (new-york-market? (dt/date-time 2015 1 1 (dec (:close new-york-hours))))))
  (is (false? (new-york-market? (dt/date-time 2015 1 1 (:close new-york-hours)))))
  (is (true? (chicago-market? (dt/date-time 2015 1 1 (:open chicago-hours)))))
  (is (true? (chicago-market? (dt/date-time 2015 1 1 (dec (:close chicago-hours))))))
  (is (false? (chicago-market? (dt/date-time 2015 1 1 (:close chicago-hours)))))
  (is (true? (tokyo-market? (dt/date-time 2015 1 1 (:open tokyo-hours)))))
  (is (true? (tokyo-market? (dt/date-time 2015 1 1 (dec (:close tokyo-hours))))))
  (is (false? (tokyo-market? (dt/date-time 2015 1 1 (:close tokyo-hours)))))
  (is (true? (hong-kong-market? (dt/date-time 2015 1 1 (:open hong-kong-hours)))))
  (is (true? (hong-kong-market? (dt/date-time 2015 1 1 (dec (:close hong-kong-hours))))))
  (is (false? (hong-kong-market? (dt/date-time 2015 1 1 (:close hong-kong-hours)))))
  (is (true? (sydney-market? (dt/date-time 2015 1 1 (:open sydney-hours)))))
  (is (true? (sydney-market? (dt/date-time 2015 1 1 (dec (:close sydney-hours))))))
  (is (false? (sydney-market? (dt/date-time 2015 1 1 (:close sydney-hours)))))
  (is (true? (wellington-market? (dt/date-time 2015 1 1 (:open wellington-hours)))))
  (is (true? (wellington-market? (dt/date-time 2015 1 1 (dec (:close wellington-hours))))))
  (is (false? (wellington-market? (dt/date-time 2015 1 1 (:close wellington-hours)))))
  (is (some #{:london} (active-markets (dt/date-time 2015 1 1 (:open london-hours)))))
  (is (some #{:frankfurt} (active-markets (dt/date-time 2015 1 1 (:open frankfurt-hours)))))
  (is (some #{:new-york} (active-markets (dt/date-time 2015 1 1 (:open new-york-hours)))))
  (is (some #{:chicago} (active-markets (dt/date-time 2015 1 1 (:open chicago-hours)))))
  (is (some #{:tokyo} (active-markets (dt/date-time 2015 1 1 (:open tokyo-hours)))))
  (is (some #{:hong-kong} (active-markets (dt/date-time 2015 1 1 (:open hong-kong-hours)))))
  (is (some #{:sydney} (active-markets (dt/date-time 2015 1 1 (:open sydney-hours)))))
  (is (some #{:wellington} (active-markets (dt/date-time 2015 1 1 (:open wellington-hours))))))