(ns machine.analyse-management.wrb-analysis.vsa
  (:require [machine.quotes.series :refer :all]
            [machine.analyse-management.quantum.utils :refer :all]
            [machine.analyse-management.wrb-analysis.utils :refer :all])
  (:import [machine.quotes.core Quotes]
           [org.apache.commons.math3.util FastMath]))


(defprotocol Volume-Spread-Analysis
  (volume-average [data n] [data n i])
  (supply-demand [data zone-types]))

(extend-type Quotes
  Volume-Spread-Analysis
  (volume-average
    (^Quotes [{:keys [^longs volume#] :as data} ^long n]
     (let [array-length (alength volume#)
           result# (double-array array-length)]
       (loop [i (- (dec array-length) n)]
         (when (>= i 0)
           (aset result# i ^double (amean (aslice volume# i (FastMath/min (dec array-length) (+ i n)))))
           (recur (dec i))))
       (assoc data :volume-average# result#))))
  (supply-demand
    (^Quotes [^Quotes {:keys [^doubles open# ^doubles high# ^doubles low#
                              ^doubles close# ^longs volume# ^doubles candle-body-midpoint#
                              ^doubles candle-bar-size#]
                       :as   data} zone-types]
     (let [array-size (alength ^objects (:time# data))
           zone# (identity-union (mapv #(get data (zone-keyword %)) zone-types))
           zone-open# (price-union (mapv #(get data (open-keyword %)) zone-types))
           zone-close# (price-union (mapv #(get data (close-keyword %)) zone-types))
           zone-size# (price-union (mapv #(get data (size-keyword %)) zone-types))
           zone-filled-by# (identity-union (mapv #(get data (filled-by-keyword %)) zone-types))
           zone-confirmation-candle# (identity-union (mapv #(get data (confirmation-candle-keyword %)) zone-types))
           zone-type# (object-union (mapv #(get data (type-keyword %)) zone-types))
           vsa-sd# (long-array array-size)
           vsa-sd-zone-nr# (long-array array-size)
           zone-used-by# (long-array array-size)]
       (loop [i (- array-size 3)]
         (when (>= i 0)
           (loop [j 1]
             (when (and (< j (- array-size i 1)) (<= j 64))
               (cond (and (== 1 (aget zone# (+ i j)))
                          (or (and (= :swing-point (aget zone-type# (+ i j))) (<= j 64))
                              (and (= :strong-continuation (aget zone-type# (+ i j))) (<= j 8)))
                          (zero? (aget zone-used-by# (+ i j)))
                          (>= (aget zone-confirmation-candle# (+ i j)) i)
                          (<= (aget zone-filled-by# (+ i j)) i)
                          (< (aget close# i) (aget zone-open# (+ i j)))
                          (> (aget close# i) (aget zone-close# (+ i j)))
                          (or
                            ; no-supply-1
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ; no-supply-2
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (> (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ; no-supply-3
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (> (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-4
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (> (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-5
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (> (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-6
                            (and (< (aget close# i) (aget close# (inc i)))
                                 (< (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-7
                            (and (< (aget close# i) (aget close# (inc i)))
                                 (== (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-8
                            (and (< (aget close# i) (aget close# (inc i)))
                                 (== (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (not= (aget close# i) (aget open# i))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-9
                            (and (< (aget close# i) (aget close# (inc i)))
                                 (== (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (not= (aget close# i) (aget open# i))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-10
                            (and (< (aget close# i) (aget close# (inc i)))
                                 (== (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (not= (aget close# i) (aget open# i))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-11
                            (and (== (aget close# i) (aget close# (inc i)))
                                 (< (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-12
                            (and (== (aget close# i) (aget close# (inc i)))
                                 (< (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (not= (aget close# i) (aget open# i))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-13
                            (and (== (aget close# i) (aget close# (inc i)))
                                 (< (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (not= (aget close# i) (aget open# i))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-14
                            (and (== (aget close# i) (aget close# (inc i)))
                                 (< (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (not= (aget close# i) (aget open# i))
                                 (< (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-15
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (<= (aget close# i) (aget close# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (== (aget close# i) (aget close# (dec i)))
                                 (< (aget close# i) (aget close# (- i 2)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (<= (aget low# i) (aget low# (- i 2)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-16
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (<= (aget close# i) (aget close# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (not= (aget close# i) (aget open# i))
                                 (== (aget close# i) (aget close# (dec i)))
                                 (< (aget close# i) (aget close# (- i 2)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (<= (aget low# i) (aget low# (- i 2)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-17
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (<= (aget close# i) (aget close# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (not= (aget close# i) (aget open# i))
                                 (== (aget close# i) (aget close# (dec i)))
                                 (< (aget close# i) (aget close# (- i 2)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (<= (aget low# i) (aget low# (- i 2)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-18
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (>= (aget close# i) (aget close# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (not= (aget close# i) (aget open# i))
                                 (== (aget close# i) (aget close# (dec i)))
                                 (< (aget close# i) (aget close# (- i 2)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (<= (aget low# i) (aget low# (- i 2)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-19
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (<= (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-20
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (not= (aget close# i) (aget open# i))
                                 (<= (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-21
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (not= (aget close# i) (aget open# i))
                                 (<= (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-22
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (not= (aget close# i) (aget open# i))
                                 (<= (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-23
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (<= (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-24
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (not= (aget close# i) (aget open# i))
                                 (<= (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-25
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (not= (aget close# i) (aget open# i))
                                 (<= (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-26
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (not= (aget close# i) (aget open# i))
                                 (<= (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-supply-27
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (<= (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2)))) ;TODO
                            ;no-supply-28
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (not= (aget close# i) (aget open# i))
                                 (<= (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2)))) ;TODO
                            ;no-supply-29
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (not= (aget close# i) (aget open# i))
                                 (<= (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2)))) ;TODO
                            ;no-supply-30
                            (and (< (aget low# i) (aget low# (inc i)))
                                 (<= (aget high# i) (aget high# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (not= (aget close# i) (aget open# i))
                                 (<= (aget close# i) (aget close# (dec i)))
                                 (<= (aget low# i) (aget low# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2)))))) ;TODO
                     (do (aset zone-used-by# (+ i j) i)
                         (aset vsa-sd# (dec i) 1)
                         (aset vsa-sd-zone-nr# i (+ i j)))
                     (and (== -1 (aget zone# (+ i j)))
                          (or (and (= :swing-point (aget zone-type# (+ i j))) (<= j 64))
                              (and (= :strong-continuation (aget zone-type# (+ i j))) (<= j 8)))
                          (zero? (aget zone-used-by# (+ i j)))
                          (>= (aget zone-confirmation-candle# (+ i j)) i)
                          (<= (aget zone-filled-by# (+ i j)) i)
                          (< (aget close# i) (aget zone-open# (+ i j)))
                          (> (aget close# i) (aget zone-close# (+ i j)))
                          (or
                            ; no-demand-1
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ; no-demand-2
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (> (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ; no-demand-3
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (> (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-4
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (> (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-5
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (> (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-6
                            (and (> (aget close# i) (aget close# (inc i)))
                                 (< (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-7
                            (and (> (aget close# i) (aget close# (inc i)))
                                 (== (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-8
                            (and (> (aget close# i) (aget close# (inc i)))
                                 (== (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (not= (aget close# i) (aget open# i))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-9
                            (and (> (aget close# i) (aget close# (inc i)))
                                 (== (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (not= (aget close# i) (aget open# i))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-10
                            (and (> (aget close# i) (aget close# (inc i)))
                                 (== (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (not= (aget close# i) (aget open# i))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-11
                            (and (== (aget close# i) (aget close# (inc i)))
                                 (< (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-12
                            (and (== (aget close# i) (aget close# (inc i)))
                                 (< (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (not= (aget close# i) (aget open# i))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-13
                            (and (== (aget close# i) (aget close# (inc i)))
                                 (< (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (not= (aget close# i) (aget open# i))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-14
                            (and (== (aget close# i) (aget close# (inc i)))
                                 (< (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (not= (aget close# i) (aget open# i))
                                 (> (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-15
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (>= (aget close# i) (aget close# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (== (aget close# i) (aget close# (dec i)))
                                 (> (aget close# i) (aget close# (- i 2)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (>= (aget high# i) (aget high# (- i 2)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-16
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (>= (aget close# i) (aget close# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (not= (aget close# i) (aget open# i))
                                 (== (aget close# i) (aget close# (dec i)))
                                 (> (aget close# i) (aget close# (- i 2)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (>= (aget high# i) (aget high# (- i 2)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-17
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (>= (aget close# i) (aget close# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (not= (aget close# i) (aget open# i))
                                 (== (aget close# i) (aget close# (dec i)))
                                 (> (aget close# i) (aget close# (- i 2)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (>= (aget high# i) (aget high# (- i 2)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-18
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (>= (aget close# i) (aget close# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (not= (aget close# i) (aget open# i))
                                 (== (aget close# i) (aget close# (dec i)))
                                 (> (aget close# i) (aget close# (- i 2)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (>= (aget high# i) (aget high# (- i 2)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-19
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (>= (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-20
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (not= (aget close# i) (aget open# i))
                                 (>= (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-21
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (not= (aget close# i) (aget open# i))
                                 (>= (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-22
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (not= (aget close# i) (aget open# i))
                                 (>= (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-23
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (>= (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-24
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (not= (aget close# i) (aget open# i))
                                 (>= (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-25
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (not= (aget close# i) (aget open# i))
                                 (>= (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-26
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (not= (aget close# i) (aget open# i))
                                 (>= (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2))))
                            ;no-demand-27
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (== (aget close# i) (aget open# i))
                                 (>= (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2)))) ;TODO
                            ;no-demand-28
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget high# i))
                                 (not= (aget close# i) (aget open# i))
                                 (>= (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2)))) ;TODO
                            ;no-demand-29
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget candle-body-midpoint# i))
                                 (not= (aget close# i) (aget open# i))
                                 (>= (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2)))) ;TODO
                            ;no-demand-30
                            (and (> (aget high# i) (aget high# (inc i)))
                                 (>= (aget low# i) (aget low# (inc i)))
                                 (<= (aget candle-bar-size# i) (aget candle-bar-size# (inc i)))
                                 (== (aget close# i) (aget low# i))
                                 (not= (aget close# i) (aget open# i))
                                 (>= (aget close# i) (aget close# (dec i)))
                                 (>= (aget high# i) (aget high# (dec i)))
                                 (< (aget volume# i) (aget volume# (inc i)))
                                 (< (aget volume# i) (aget volume# (+ i 2)))))) ;TODO
                     (do (aset zone-used-by# (+ i j) i)
                         (aset vsa-sd# (dec i) -1)
                         (aset vsa-sd-zone-nr# i (+ i j)))
                     :else (recur (inc j)))))
           (recur (dec i))))
       (-> data
           (assoc :vsa-sd# vsa-sd#)
           (assoc :vsa-sd-zone-nr# vsa-sd-zone-nr#))))))


;(defn effort
;  (^Quotes [^Quotes data zone-types]
;   (effort data zone-types 0))
;  (^Quotes [^Quotes data zone-types look-back]
;   (let [array-size (alength ^objects (:time data))
;         loop-limit (- array-size 2)
;         ^doubles high# (:high data)
;         ^doubles low# (:low data)
;         ^doubles close# (:close data)
;         ^longs volume# (:volume data)
;         ^doubles volume-average# (:volume-average data)
;         ^doubles candle-bar-size# (:candle-range-size data)
;         ^doubles upper-shadow# (:candle-upper-shadow# data)
;         ^doubles bottom-shadow# (:candle-bottom-shadow# data)
;         ^longs wrb-body# (:wrb-body# data)
;         ^longs zone-inside# (identity-union (mapv #(get data (inside-keyword %)) zone-types))
;         ^longs zone-inside-nr# (identity-union (mapv #(get data (inside-nr-keyword %)) zone-types))
;         ^longs vsa-effort# (long-array array-size)]
;     (loop [i 1]
;       (when (< i loop-limit)
;         (when-let [z (aget zone-inside-nr# i)]
;           (cond
;             (and (or (== look-back 0) (<= (- z i) look-back))
;                  (== 1 (aget zone-inside# i))
;                  (== 1 (aget wrb-body# i))
;                  (> (aget high# i)
;                     (aget high# (inc i)))
;                  (>= (aget low# i)
;                      (aget low# (inc i)))
;                  (or (and (== (aget candle-bar-size# i)
;                               (aget candle-bar-size# (inc i)))
;                           (< (/ (aget bottom-shadow# i)
;                                 (aget candle-bar-size# i))
;                              0.1)
;                           (< (/ (aget upper-shadow# i)
;                                 (aget candle-bar-size# i))
;                              0.1))
;                      (and (> (aget candle-bar-size# i)
;                              (aget candle-bar-size# (inc i)))
;                           (< (/ (aget bottom-shadow# i)
;                                 (aget candle-bar-size# i))
;                              0.2)
;                           (< (/ (aget upper-shadow# i)
;                                 (aget candle-bar-size# i))
;                              0.2)))
;                  (> (* (+ (aget high# i) (aget low# i)) 0.5)
;                     (aget high# (inc i)))
;                  (> (aget close# i)
;                     (aget close# (inc i)))
;                  (> (aget volume# i)
;                     (aget volume# (inc i)))
;                  (or (> (* 2 (aget volume-average# i))
;                         (aget volume# i)
;                         (aget volume-average# i))
;                      (> (* 4 (aget volume-average# i))
;                         (aget volume# i)
;                         (* 2 (aget volume-average# i)))
;                      (and (> (aget volume-average# i)
;                              (aget volume# i))
;                           (> (aget volume# i)
;                              (aget volume# (inc i)))
;                           (> (aget volume# i)
;                              (aget volume# (+ i 2))))))
;             (aset vsa-effort# i 1)
;
;             (and (or (== look-back 0) (<= (- z i) look-back))
;                  (== -1 (aget zone-inside# i))
;                  (== -1 (aget wrb-body# i))
;                  (< (aget low# i)
;                     (aget low# (inc i)))
;                  (<= (aget high# i)
;                      (aget high# (inc i)))
;                  (or (and (== (aget candle-bar-size# i)
;                               (aget candle-bar-size# (inc i)))
;                           (< (/ (aget bottom-shadow# i)
;                                 (aget candle-bar-size# i))
;                              0.1)
;                           (< (/ (aget upper-shadow# i)
;                                 (aget candle-bar-size# i))
;                              0.1))
;                      (and (> (aget candle-bar-size# i)
;                              (aget candle-bar-size# (inc i)))
;                           (< (/ (aget bottom-shadow# i)
;                                 (aget candle-bar-size# i))
;                              0.2)
;                           (< (/ (aget upper-shadow# i)
;                                 (aget candle-bar-size# i))
;                              0.2)))
;                  (< (* (+ (aget high# i) (aget low# i)) 0.5)
;                     (aget low# (inc i)))
;                  (< (aget close# i)
;                     (aget close# (inc i)))
;                  (> (aget volume# i)
;                     (aget volume# (inc i)))
;                  (or (> (* 2 (aget volume-average# i))
;                         (aget volume# i)
;                         (aget volume-average# i))
;                      (> (* 4 (aget volume-average# i))
;                         (aget volume# i)
;                         (* 2 (aget volume-average# i)))
;                      (and (> (aget volume-average# i)
;                              (aget volume# i))
;                           (> (aget volume# i)
;                              (aget volume# (inc i)))
;                           (> (aget volume# i)
;                              (aget volume# (+ i 2))))))
;             (aset vsa-effort# i -1)))
;         (recur (inc i))))
;     (-> data
;         (assoc :vsa-effort vsa-effort#)))))
